<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Carrinho' => $baseDir . '/model/Carrinho.class.php',
    'Categorias' => $baseDir . '/model/Categorias.class.php',
    'Clientes' => $baseDir . '/model/Clientes.class.php',
    'Conexao' => $baseDir . '/model/Conexao.class.php',
    'Config' => $baseDir . '/model/Config.class.php',
    'Correios' => $baseDir . '/model/Correios.class.php',
    'Deposit' => $baseDir . '/model/Desposit.class.php',
    'EasyPeasyICS' => $vendorDir . '/phpmailer/phpmailer/extras/EasyPeasyICS.php',
    'EnviarEmail' => $baseDir . '/model/EnviarEmail.class.php',
    'Historic' => $baseDir . '/model/Historic.class.php',
    'ImageUpload' => $baseDir . '/model/ImageUpload.class.php',
    'Itens' => $baseDir . '/model/ItensPedido.class.php',
    'Login' => $baseDir . '/model/Login.class.php',
    'PHPMailer' => $vendorDir . '/phpmailer/phpmailer/class.phpmailer.php',
    'PHPMailerOAuth' => $vendorDir . '/phpmailer/phpmailer/class.phpmaileroauth.php',
    'PHPMailerOAuthGoogle' => $vendorDir . '/phpmailer/phpmailer/class.phpmaileroauthgoogle.php',
    'POP3' => $vendorDir . '/phpmailer/phpmailer/class.pop3.php',
    'PagamentoPS' => $baseDir . '/model/PagamentoPS.class.php',
    'Paginacao' => $baseDir . '/model/Paginacao.class.php',
    'Pedidos' => $baseDir . '/model/Pedidos.class.php',
    'Produtos' => $baseDir . '/model/Produtos.class.php',
    'ProdutosImages' => $baseDir . '/model/ProdutosImages.class.php',
    'Rotas' => $baseDir . '/model/Rotas.class.php',
    'SMTP' => $vendorDir . '/phpmailer/phpmailer/class.smtp.php',
    'Sistema' => $baseDir . '/model/Sistema.class.php',
    'Template' => $baseDir . '/model/Template.class.php',
    'Transfer' => $baseDir . '/model/Transfer.class.php',
    'User' => $baseDir . '/model/User.class.php',
    'UserBasic' => $baseDir . '/model/UserBaisc.class.php',
    'UserInterface' => $baseDir . '/model/UserInterface.php',
    'UserPremium' => $baseDir . '/model/UserPremium.class.php',
    'UserSalary' => $baseDir . '/model/UserSalary.class.php',
    'Withdraw' => $baseDir . '/model/Withdraw.class.php',
    'ntlm_sasl_client_class' => $vendorDir . '/phpmailer/phpmailer/extras/ntlm_sasl_client.php',
    'phpmailerException' => $vendorDir . '/phpmailer/phpmailer/class.phpmailer.php',
);
